"""baseline_atlas_schema

Revision ID: 4fcfc8621e91
Revises:
Create Date: 2026-04-12 06:37:14.704644

"""

from typing import Sequence, Union

from alembic import op  # type: ignore[attr-defined]
import sqlalchemy as sa


revision: str = "4fcfc8621e91"
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # Baseline: aligns atlas_* tables with current ORM models.
    # JIP-owned tables (de_*, alembic_version) are deliberately untouched.
    op.alter_column(
        "atlas_decisions",
        "signal",
        existing_type=sa.VARCHAR(length=10),
        type_=sa.Enum("BUY", "SELL", "HOLD", "WATCH", name="decisionsignalenum"),
        existing_nullable=False,
    )
    op.alter_column(
        "atlas_decisions",
        "action",
        existing_type=sa.VARCHAR(length=20),
        type_=sa.Enum("PENDING", "ACCEPTED", "IGNORED", "OVERRIDDEN", name="decisionactionenum"),
        existing_nullable=False,
        existing_server_default=sa.text("'PENDING'::character varying"),
    )
    op.alter_column(
        "atlas_decisions",
        "is_deleted",
        existing_type=sa.BOOLEAN(),
        nullable=False,
        existing_server_default=sa.text("false"),
    )
    op.alter_column(
        "atlas_intelligence",
        "is_deleted",
        existing_type=sa.BOOLEAN(),
        nullable=False,
        existing_server_default=sa.text("false"),
    )
    op.drop_index(op.f("ix_atlas_intel_agent"), table_name="atlas_intelligence")
    op.drop_index(op.f("ix_atlas_intel_finding_type"), table_name="atlas_intelligence")
    op.create_index(
        op.f("ix_atlas_intelligence_agent_name"),
        "atlas_intelligence",
        ["agent_name"],
        unique=False,
    )
    op.create_index(
        op.f("ix_atlas_intelligence_entity_id"),
        "atlas_intelligence",
        ["entity_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_atlas_intelligence_entity_type"),
        "atlas_intelligence",
        ["entity_type"],
        unique=False,
    )
    op.create_index(
        op.f("ix_atlas_intelligence_finding_type"),
        "atlas_intelligence",
        ["finding_type"],
        unique=False,
    )
    op.alter_column(
        "atlas_watchlists",
        "is_deleted",
        existing_type=sa.BOOLEAN(),
        nullable=False,
        existing_server_default=sa.text("false"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "atlas_watchlists",
        "is_deleted",
        existing_type=sa.BOOLEAN(),
        nullable=True,
        existing_server_default=sa.text("false"),
    )
    op.drop_index(op.f("ix_atlas_intelligence_finding_type"), table_name="atlas_intelligence")
    op.drop_index(op.f("ix_atlas_intelligence_entity_type"), table_name="atlas_intelligence")
    op.drop_index(op.f("ix_atlas_intelligence_entity_id"), table_name="atlas_intelligence")
    op.drop_index(op.f("ix_atlas_intelligence_agent_name"), table_name="atlas_intelligence")
    op.create_index(
        op.f("ix_atlas_intel_finding_type"),
        "atlas_intelligence",
        ["finding_type"],
        unique=False,
    )
    op.create_index(
        op.f("ix_atlas_intel_agent"), "atlas_intelligence", ["agent_name"], unique=False
    )
    op.alter_column(
        "atlas_intelligence",
        "is_deleted",
        existing_type=sa.BOOLEAN(),
        nullable=True,
        existing_server_default=sa.text("false"),
    )
    op.alter_column(
        "atlas_decisions",
        "is_deleted",
        existing_type=sa.BOOLEAN(),
        nullable=True,
        existing_server_default=sa.text("false"),
    )
    op.alter_column(
        "atlas_decisions",
        "action",
        existing_type=sa.Enum(
            "PENDING", "ACCEPTED", "IGNORED", "OVERRIDDEN", name="decisionactionenum"
        ),
        type_=sa.VARCHAR(length=20),
        existing_nullable=False,
        existing_server_default=sa.text("'PENDING'::character varying"),
    )
    op.alter_column(
        "atlas_decisions",
        "signal",
        existing_type=sa.Enum("BUY", "SELL", "HOLD", "WATCH", name="decisionsignalenum"),
        type_=sa.VARCHAR(length=10),
        existing_nullable=False,
    )
    # JIP alembic_version table is untouched on downgrade.
